# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "bbdd1" do |bbdd1|
    bbdd1.vm.box = "centos/7"
    bbdd1.vm.hostname = "Centos7BBDD1"
    bbdd1.vm.box_url = "centos/7"
    bbdd1.vm.network :public_network, ip: "192.168.1.23"
    bbdd1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--name", "VM-BBDD1"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 1]
    end
    $COMMANDS = <<-'BLOCK'
    sudo yum -y install dnf
    sudo dnf -y install dnf-plugins-core
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
    sudo systemctl restart sshd;
    BLOCK
    config.vm.provision "shell", inline: $COMMANDS
  end
  config.vm.define "bbdd2" do |bbdd2|
    bbdd2.vm.box = "centos/7"
    bbdd2.vm.hostname = "Centos7BBDD2"
    bbdd2.vm.box_url = "centos/7"
    bbdd2.vm.network :public_network, ip: "192.168.1.24"
    bbdd2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--name", "VM-BBDD2"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 1]
    end
    $COMMANDS = <<-'BLOCK'
    sudo yum -y install dnf
    sudo dnf -y install dnf-plugins-core
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
    sudo systemctl restart sshd;
    BLOCK
    config.vm.provision "shell", inline: $COMMANDS
  end
end